"""
Django settings for snappdf_core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+-e^^pu5hu-+366)(rh)c&!jq&a!m!jm3$3d%+a&hnqwv2%sf5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "your-api.example.com",
    "*"
]

CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com','http://3.107.98.250'
                       'https://*.onrender.com', 
                       'http://3.107.98.250', 
                      'http://umerlabs.tech', 
                    'http://www.umerlabs.tech']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pdf_tools',
    'rest_framework',
    'corsheaders',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- Yeh line yahan add karein
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'snappdf_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snappdf_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Uploads above this size are streamed to disk by Django instead of held in RAM
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# Custom limits used by the merge view
PDF_MERGE_MAX_FILES = 20
PDF_MERGE_MAX_FILE_SIZE = 50 * 1024 * 1024   # 50 MB per file


PDF_TO_JPG_MAX_FILE_SIZE = 50 * 1024 * 1024   # 50 MB
PDF_TO_JPG_MAX_PAGES = 100
PDF_TO_JPG_DEFAULT_DPI = 150
PDF_TO_JPG_MAX_DPI = 300
PDF_TO_JPG_JPEG_QUALITY = 85
PDF_TO_JPG_TIMEOUT = 60                        # seconds per Poppler call

# Protect PDF
PDF_PROTECT_MAX_FILE_SIZE = 50 * 1024 * 1024
PDF_PROTECT_MAX_PASSWORD_LENGTH = 128

# Compress PDF
PDF_COMPRESS_MAX_FILE_SIZE = 100 * 1024 * 1024
PDF_COMPRESS_TIMEOUT = 120                 # seconds before Ghostscript is killed
GHOSTSCRIPT_BINARY = "gs"                  # or an absolute path, e.g. /usr/bin/gs

# Shared by PDF to Text / Word / Speech
PDF_TEXT_MAX_FILE_SIZE = 50 * 1024 * 1024
PDF_TEXT_MAX_PAGES = 500

# PDF to Word (layout analysis is CPU-heavy, so keep this lower)
PDF_WORD_MAX_FILE_SIZE = 30 * 1024 * 1024
PDF_WORD_MAX_PAGES = 100

# PDF to Speech (gTTS makes one web request per ~100 characters)
PDF_SPEECH_MAX_FILE_SIZE = 20 * 1024 * 1024
PDF_SPEECH_MAX_CHARS = 20000
PDF_SPEECH_TIMEOUT = 30          # seconds per gTTS HTTP request

# Split PDF
PDF_SPLIT_MAX_FILE_SIZE = 100 * 1024 * 1024
PDF_SPLIT_MAX_PAGES = 2000
PDF_SPLIT_MAX_RANGES = 200          # max comma-separated tokens in "pages"
PDF_SPLIT_MAX_PAGES_STRING = 1000   # max length of the "pages" string

# Unlock PDF
PDF_UNLOCK_MAX_FILE_SIZE = 100 * 1024 * 1024
PDF_UNLOCK_MAX_PASSWORD_LENGTH = 128


CORS_EXPOSE_HEADERS = ["Content-Disposition", "X-Original-Size", "X-Compressed-Size"]


CORS_ALLOWED_ORIGINS = [
    "https://your-frontend.example.com",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_EXPOSE_HEADERS = [
    "Content-Disposition",
    "X-Original-Size",
    "X-Compressed-Size",
]


# PDF to Excel
PDF_EXCEL_MAX_FILE_SIZE = 50 * 1024 * 1024
PDF_EXCEL_MAX_PAGES = 200
PDF_EXCEL_MAX_CELLS = 200_000

# Excel to PDF
EXCEL_PDF_MAX_FILE_SIZE = 20 * 1024 * 1024
EXCEL_PDF_MAX_SHEETS = 20
EXCEL_PDF_MAX_CELLS = 50_000
EXCEL_PDF_MAX_CELL_CHARS = 60
# Optional TTF for non-Latin text (Helvetica only covers Latin-1):
# PDF_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

# Image to PDF
IMAGE_PDF_MAX_FILE_SIZE = 30 * 1024 * 1024
IMAGE_PDF_MAX_PIXELS = 50_000_000       # ~7000 x 7000

# Crop PDF
PDF_CROP_MAX_FILE_SIZE = 100 * 1024 * 1024
PDF_CROP_MAX_PAGES = 2000

PDF_EDIT_MAX_FILE_SIZE = 100 * 1024 * 1024
PDF_EDIT_MAX_PAGES = 1000
PDF_EDIT_MAX_ELEMENTS = 500
PDF_EDIT_MAX_TEXT_CHARS = 5000
PDF_EDIT_MAX_JSON_BYTES = 2 * 1024 * 1024
# Optional Unicode font (Helvetica covers Latin-1 only). Already used by Excel to PDF:
# PDF_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

# Authorization
AUTHORIZATION = "Bearer <clerk-session-token>"

# Custom error handler for 401 Unauthorized
HANDLER_401_UNAUTHORIZED = "snappdf_core.views.custom_401_unauthorized"
